---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: tke
spec:
  ports:
    - name: https
      port: 2379
      protocol: TCP
      targetPort: 2379
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd
  namespace: tke
subsets:
- addresses:
{{- range $element := .Servers }}
  - ip: {{ $element -}}
{{ end }}
  ports:
  - name: https
    port: 2379
    protocol: TCP