---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: tke
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: nginx
          image: {{ .Image }}
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx
      volumes:
        - name: config-volume
          configMap:
            name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: tke
data:
  nginx.conf: |
    error_log stderr info;
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 9480;
            location /healthz {
                return 200 "ok";
            }
        }
    }
    stream {
{{- if .EnableGateway }}
        upstream http {
            {{range $element := .Servers}} server {{$element}}:9442; {{end}}
        }
        server {
            listen 80;
            proxy_pass http;
        }

        upstream https {
            {{range $element := .Servers}} server {{$element}}:9441; {{end}}
        }
        server {
            listen 443;
            proxy_pass https;
        }
{{- end }}

{{- if .EnableKeepalived }}
        upstream apiserver {
            {{range $element := .Servers}} server {{$element}}:6443; {{end}}
        }
        server {
            listen 8443;
            proxy_pass apiserver;
        }
{{- end }}
    }