apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: keepalived
  name: keepalived
  namespace: tke
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      containers:
        - image: {{ .Image }}
          name: keepalived
          args:
            - --log-console
            - --dont-fork
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /etc/keepalived/
              name: config-volume
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      volumes:
        - configMap:
            defaultMode: 420
            name: keepalived
          name: config-volume
---
apiVersion: v1
data:
  keepalived.conf: |
    global_defs {
       enable_script_security
       script_user root
    }
    vrrp_script chk_tke {
       script "/bin/bash -c 'curl -m1 -s http://127.0.0.1/healthz -o/dev/null'"
       interval 2
       weight -10
       fall 1
       rise 1
    }
    vrrp_instance VI_1 {
        state BACKUP
        interface eth0
        virtual_router_id 51
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass 1111
        }
        virtual_ipaddress {
            {{ .VIP }}
        }
        track_script {
          chk_tke
        }
    }
kind: ConfigMap
metadata:
  name: keepalived
  namespace: tke